// Mapeo de nombres de equipos: API-Football (inglés) -> APProde (español)
// Las claves deben coincidir EXACTAMENTE con el campo "name" que devuelve la API
export const TEAM_NAME_MAP = {
  'Argentina': 'Argentina',
  'Brazil': 'Brasil',
  'France': 'Francia',
  'Spain': 'España',
  'Portugal': 'Portugal',
  'Germany': 'Alemania',
  'England': 'Inglaterra',
  'Netherlands': 'Países Bajos',
  'Belgium': 'Bélgica',
  'Uruguay': 'Uruguay',
  'Colombia': 'Colombia',
  'Mexico': 'México',
  'Ecuador': 'Ecuador',
  'Croatia': 'Croacia',
  'Switzerland': 'Suiza',
  'Senegal': 'Senegal',
  'Japan': 'Japón',
  'South Korea': 'Corea del Sur',
  'Korea Republic': 'Corea del Sur',
  'Morocco': 'Marruecos',
  'Ghana': 'Ghana',
  'Australia': 'Australia',
  'USA': 'EE.UU.',
  'United States': 'EE.UU.',
  'Canada': 'Canadá',
  'Saudi Arabia': 'Arabia Saudita',
  'Turkey': 'Turquía',
  'Türkiye': 'Turquía',
  'Qatar': 'Qatar',
  'Italy': 'Italia',
  'Norway': 'Noruega',
  'Scotland': 'Escocia',
  'Austria': 'Austria',
  'Algeria': 'Argelia',
  'Iran': 'Irán',
  'IR Iran': 'Irán',
  'Egypt': 'Egipto',
  'Panama': 'Panamá',
  'Uzbekistan': 'Uzbekistán',
  'Jamaica': 'Jamaica',
  'Bosnia and Herzegovina': 'Bosnia',
  'Bosnia & Herzegovina': 'Bosnia',
  'Cape Verde': 'Cabo Verde',
  'Cape Verde Islands': 'Cabo Verde',
  'Ivory Coast': 'Costa de Marfil',
  "Côte d'Ivoire": 'Costa de Marfil',
  'Curacao': 'Curazao',
  'Curaçao': 'Curazao',
  'Haiti': 'Haití',
  'Iraq': 'Irak',
  'Jordan': 'Jordania',
  'New Zealand': 'Nueva Zelanda',
  'Paraguay': 'Paraguay',
  'Czech Republic': 'Rep. Checa',
  'Czechia': 'Rep. Checa',
  'South Africa': 'Sudáfrica',
  'Sweden': 'Suecia',
  'Tunisia': 'Túnez',
}

// Convierte nombre de equipo de la API a nuestro nombre en español
export function mapTeamName(apiName) {
  return TEAM_NAME_MAP[apiName] || apiName
}
